### PR TITLE
Announce range of choice (#17)

### PR DESCRIPTION
**Pull request by LauraneS**
- Quick explanation of what we are changing + announce range of choice

### CODE REVIEW

**Comment by RusticFlare** [comment]
Nice

**Comment by tjvr** [comment]
The explanation of what we're changing—eg. "how loud"—is helpful (if a little wordy). Very nice! :)

**Comment by LauraneS** [comment]
> (if a little wordy)

I couldn't come up with more concise sentences, but if people have better phrasing, by all means! I think the worst is the explanation of "release"...

**Comment by isaac-dunn** [comment]
Yeah I think they're all good apart from that. Maybe just go with `release` = the length of the note?

**Pull request merged**
