### PR TITLE
Undo and redo added

### PR DESCRIPTION
**Pull request by Psyclone150**
Fixes issue #14. The user can press Ctrl+Z for undo and Ctrl+Y for redo.
Also fixes a bug related to binding cubelets. Does not impose a hard
limit on the number of actions that may be remembered. Any opinions on
what would be a sensible limit?

### CODE REVIEW

**Comment by tjvr** [comment]
Please remove commented code ([example](https://github.com/cambridge-alpha-team/unvisual-frontend/pull/55/files#diff-77ab163850ef0fa98d6a9ee9fb6bbcafR40)) and `console.log(…)` statements.

**Comment by LauraneS** [comment]
The undo command seems to work fine for me, but whenever I try to redo something, it displays "there is nothing to redo."

Also, when there is nothing to undo anymore, the error displayed is pretty confusing: "ERROR: The currently selected piece of code is not recognised as a child by its parent."

**Comment by Psyclone150** [comment]
@blob8108 Sorry, I overlooked those. They're gone now.
@LauraneS Could you please describe exactly what you did that caused those effects? Undo and redo both worked fine in the cases I tested (which included adding and deleting multiple nodes, changing values and assigning cubelets).

**Comment by Psyclone150** [comment]
Actually I bet there'll be a bug related to adding/deleting fx nodes because of reparenting of child nodes. That will be non-trivial to fix. Shall I work on it as part of this pull request, or simply disable that for now (should be quicker) and work on that issue afterwards in a separate pull request?

**Comment by RusticFlare** [comment]
change `reGenerate` to `regenerate` and fix the bug when redoing `fx`

**Comment by RusticFlare** [comment]
If I create an `fx` then press `ctrl+z` to undo, then press `ctrl+y` to redo then when I try to select the second item in the `fx` (third if you count the `fx name`) then it jumps up a level in the tree. This is causing other issues with adding and deleting code inside remade `fx`'s. It will also read out "0 of 1" selected when it should read "2 of X".

**Comment by Psyclone150** [comment]
Does it work now?

**Comment by RusticFlare** [comment]
Seems good to me. I'm going to work on the conflicts.

**Pull request merged**
