### PR TITLE
Add numpad key support, again

### LINKED ISSUE #54: Arrow keys captured by screen reader
Now that the hack supporting the num pad arrow keys has been removed, only the arrow keys are supported for navigation of the tree. However, these are captured by the screen reader.

I personally think that using the num pad was a good idea, so perhaps we could support them in a non-hacky way?

### PR DESCRIPTION
**Pull request by tjvr**
Fixes #54

This makes the keys `2`, `4`, `6`, `8` on the num pad function as arrow keys `↓`, `←`, `→`, `↑`.

### CODE REVIEW

**Comment by RusticFlare** [comment]
(also the formatting...)

**Comment by tjvr** [comment]
Whoops, I forgot to use tabs instead of spaces.

**Comment by isaac-dunn** [comment]
This only seems to work when numlock is off, which is a start, but it would be nice to have it work when numlock is on as well.

**Comment by isaac-dunn** [comment]
It's sufficient for now, though, I suppose.

**Comment by tjvr** [comment]
> when numlock is off

Right. The numlock key on the Macs doesn't seem to work... if you can figure out keycodes for _with_ numlock, add them.

**Pull request merged**
