### PR TITLE
Fixing issue #18

### PR DESCRIPTION
**Pull request by RusticFlare**
change increment values for sleep and tempo. fixes issue #18

### CODE REVIEW

**Comment by tjvr** [comment]
5-bpm increments may be too fast. I intended #18 to provoke discussion about the best step size for all of the values, not just tempo.

I also note here that ValueNode does not have a clean design: amongst other things, `step` should be an _argument_, along with `min` and `max`.

**Comment by RusticFlare** [comment]
There is now an option to define step size in the constructor for ValueNode's

**Comment by RusticFlare** [comment]
I think we should leave the min for sleep as 0 so that it works better for the cubelets

**Comment by tjvr** [comment]
> it works better for the cubelets

I don't think that's true.

**Comment by RusticFlare** [comment]
I think it is because if you turn a cubelet all the way down then you expect 0. It would then sound like a chord.

**Comment by isaac-dunn** [comment]
That's not a bad point, but I think that having it so that if you turn the cubelet all the way down just makes it very fast would also be fine, whereas having `sleep 0` in general could definitely cause problems.

**Comment by RusticFlare** [comment]
Can you please give me an example of a problem? I can't think of one. Sorry if this sounds pedantic.

**Comment by isaac-dunn** [comment]
No worries. I just meant that having an instruction that does nothing isn't intuitive at all - if it does nothing then why do we allow it? For example, the user I was working with at the meeting didn't make the connection that the number is the number of beats, so when they wanted a very short sleep, they went for the minimum value of sleep, which didn't work as expected. In particular, the loop consisted of `play 100 sleep 0` or something, so that running the code broke Sonic Pi.

I don't think that risking this kind of problem is worth it for the questionable advantage of being able to have a `sleep 0` when using the cubelets.

**Comment by isaac-dunn** [comment]
In fact, you can run into the same kind of problem when using the cubelets. If the code was `play 88 sleep {cubelet value}` then this would break Sonic Pi if the cubelet value came out as `0`.

**Comment by RusticFlare** [comment]
Fair enough. I'll fix it later.

**Comment by RusticFlare** [comment]
Fixed. I think this is ready to be merged now.

**Pull request merged**
