### PR TITLE
Fixing issue resolve #16

### LINKED ISSUE #16: Keyboard focus may get lost
Sometimes, the screen reader steals focus away from our webapp. This seems to happen when pressing any of the arrow keys. We had to fix this several times during the usability test, by pressing the magic shortcut `⇧⌃⌥↓` (which moves Voiceover's focus into the web page).

To fix this: make sure you `return false;` from every event handler.

### PR DESCRIPTION
**Pull request by RusticFlare**
Adding return false statements resolve #16

### CODE REVIEW

**Comment by tjvr** [comment]
Can you remove `SynthNode.js` from this PR? Thanks.

**Comment by RusticFlare** [comment]
resolve #16

**Comment by tjvr** [comment]
To fix this fully, also replace every `break` statement in `handleKey()` with `return false;`.

(`handleKey()` was a quick hack to make the numpad keys work; we should probably find a better long-term solution, such as patching Mousetrap)

**Comment by RusticFlare** [comment]
Done

**Comment by LauraneS** [comment]
This fixes the issue with losing the focus, but on refresh, the screen reader starts by reading out all the Sonic Pi code written on the page, until arrow keys are pressed, which gets us back into the normal mode of reading out the line the key is pointing at.

**Comment by tjvr** [comment]
> the screen reader starts by reading out all the Sonic Pi code written on the page

@LauraneS: make a new issue for this.

**Pull request merged**
