### PR TITLE
Empty loops; can add to start of a loop

### LINKED ISSUE #76: Adding a note at the start of a loop; deleting a loop's only child node
It would make sense for these actions to be possible. I'll make a start on it right away. The plan is to have an extra option in add mode if a loop is currently selected, so that you can either add the new node after the loop or as the first item in the loop.

### PR DESCRIPTION
**Pull request by Psyclone150**
Fixes #76. You can now delete all child nodes of a loop and have the
option of adding a new node to the start of a loop as an alternative to
adding nodes after the loop, if a loop is currently selected.

### CODE REVIEW

**Comment by RusticFlare** [comment]
Don't allow the user to add a loop in a loop.

**Comment by RusticFlare** [comment]
If I add something at the start of a loop then I start adding code as children for everything (instead of after them). This bug needs fixing. Also can you please try and fix the merge conflicts. Thanks

**Comment by RusticFlare** [comment]
This seems good to me, I'm going to have a look at the merge conflicts.

**Comment by RusticFlare** [comment]
I've fixed the conflicts (YIPPEE!!!), but have also found another bug (YIPPEE!!!). If you try to add an `fx` as the first piece of code in a `loop` then it is wrongly added around the `root`'s children.

**Comment by RusticFlare** [comment]
If the first thing you do is add code first in a loop it adds the wrong code
- selecting `play` adds a `loop`
- selecting `sleep` adds a `play`
- selecting `fx` adds a `sleep`

After adding code from inside a `loop` then this does't happen

**Comment by Psyclone150** [comment]
I think I've fixed those two bugs now. Does it seem alright?

**Comment by RusticFlare** [comment]
Sorry, I've found another bug. If you navigate inside a `loop` and add anything; then make the `tempo` your `activeNode`; then try to add code, you add the wrong code:
- selecting `loop` adds a `play`
- selecting `play` adds a `sleep`
- selecting `sleep` adds a `fx`

**Comment by Psyclone150** [comment]
How about now?

**Comment by LauraneS** [comment]
Think it works!

**Comment by Psyclone150** [comment]
Great! Shall I merge it now?

**Comment by RusticFlare** [comment]
I'm just going to test it now.

**Comment by RusticFlare** [comment]
I now can't delete everything inside a `loop`.

**Comment by RusticFlare** [comment]
I just merged Isaac's code so I'm going to fix those conflicts.

**Comment by Psyclone150** [comment]
Thanks for getting this all sorted for me! Sorry I wasn't around to help out at the end.

**Pull request merged**
