### PR TITLE
Remove tree levels

### PR DESCRIPTION
**Pull request by RusticFlare**
Removes an unnecessary tree level from Sample and Synth

### CODE REVIEW

**Comment by tjvr** [comment]
What thing was this hoping to change?

**Comment by RusticFlare** [comment]
There was an unnecessary tree level between selecting a synth or sample and I wrote some code to remove it, but I decided it would be better to see if the extra level was necessary for other values.

**Comment by RusticFlare** [comment]
This could fix #49 if we think it is the best way.

**Comment by LauraneS** [comment]
I like it - It definitely makes more sense, since this is the only parameter we need to set.

**Pull request merged**
